name: CI

on:
  pull_request:

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: TypeScript check
        run: bun run type-check
      - name: Biome check
        run: bun run ci
      - name: Next.js build
        run: bun run build
