name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.8
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: TypeScript check
        run: bun run type-check
      - name: Biome check
        run: bun run ci
      - name: Next.js build
        run: bun run build
  deploy-storybook:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: bun install --frozen-lockfile
          build_command: bun run build-storybook
          path: storybook-static
