name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.8
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: TypeScript check
        run: bun run type-check
      - name: Biome check
        run: bun run ci
      - name: Run tests
        run: bun run test
      - name: Generate coverage
        run: bun run coverage
      - name: Next.js build
        run: bun run build
